In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\Web_Scrapping_project\\Amazon_laptops.csv")
df.head(10)
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        550 non-null    str
 1   price        543 non-null    str
 2   rating       501 non-null    float64
 3   brand        550 non-null    str
 4   ram          514 non-null    str
 5   ssd_storage  512 non-null    str
 6   color        474 non-null    str
 7   processor    385 non-null    str
dtypes: float64(1), str(7)
memory usage: 34.5 KB

           rating
count  501.000000
mean     4.070060
std      0.769819
min      1.000000
25%      3.600000
50%      4.100000
75%      4.700000
max      5.000000

In [4]:
df.isnull().sum()

title            0
price            7
rating          49
brand            0
ram             36
ssd_storage     38
color           76
processor      165
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(262)

In [6]:
df.replace({"N/A":np.nan})

,title,price,rating,brand,ram,ssd_storage,color,processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"Dell 15, Intel Core 13th Gen i5-1334U, FHD, 15...","69,990",3.8,Dell,16GB,512GB,Grey,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
545,Apple 2026 MacBook Air 15″ Laptop with M5 chip...,"2,00,490",4.7,Apple,16GB,1TB,NaN,NaN
546,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
547,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.7,Apple,8GB,256GB,Silver,NaN
548,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"5,89,990",4.3,Apple,48GB,2TB,Black,NaN
549,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","81,490",5.0,Dell,16GB,NaN,NaN,Intel

In [7]:
# converting the numerical columns into the numeric

df['rating']=pd.to_numeric(df['rating'],errors="coerce")

In [8]:
#  cleane the price column
df['price']=df['price'].str.replace({",":'','₹':""})
df['price']=pd.to_numeric(df['price'],errors='coerce')

In [9]:
# checking their data types
print('price data type= ',df['price'].dtypes)
print('rating data type= ',df['rating'].dtypes)

price data type=  float64
rating data type=  float64

In [10]:
df

,title,price,rating,brand,ram,ssd_storage,color,processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...",75990.0,3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...",69990.0,3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,44999.0,4.0,Lenovo,8GB,512GB,Silver,AMD
3,"Dell 15, Intel Core 13th Gen i5-1334U, FHD, 15...",69990.0,3.8,Dell,16GB,512GB,Grey,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,73990.0,4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
545,Apple 2026 MacBook Air 15″ Laptop with M5 chip...,200490.0,4.7,Apple,16GB,1TB,NaN,NaN
546,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,73990.0,4.8,Apple,8GB,256GB,Indigo,NaN
547,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,73990.0,4.7,Apple,8GB,256GB,Silver,NaN
548,Apple 2026 MacBook Pro Laptop with M5 Max chip...,589990.0,4.3,Apple,48GB,2TB,Black,NaN
549,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...",81490.0,5.0,Dell,16GB,NaN,NaN,Intel

In [11]:
# clean ram column

df['ram']=df['ram'].str.replace("GB",'')
df['ram']=pd.to_numeric(df['ram'],errors="coerce")

df['ram'].unique()

array([ 16.,   8.,  nan,   4.,  12.,  24.,   6.,  32., 128.,  64.,  36.,
        48.])

In [12]:
# cleaning the storage column
def sto(i):
    if isinstance(i,str):
        if "TB" in i:
            i=i.replace("TB",'')
            return int(i)*1024
        elif "GB" in i:
            i=i.replace("GB",'')
            return int(i)
        else:
            return i

df['ssd_storage']=df['ssd_storage'].apply(sto)


# df['ssd_storage']=pd.to_numeric(df['ssd_storage'],errors="coerce")

In [13]:
# fill the missing values in ram and ssd storage
ram_median=df['ram'].median()
df['ram']=df['ram'].fillna(ram_median)

ssd_median=df["ssd_storage"].median()
df['ssd_storage']=df['ssd_storage'].fillna(ssd_median)

In [14]:
# convert the ram amd storage column into int

df[["ram",'ssd_storage']]=df[["ram",'ssd_storage']].astype("int")

In [15]:
df['title'].dropna(inplace=True)

In [16]:
# converting the brand names in all first word capital

df['brand'].unique()
df['brand']=df['brand'].str.strip().str.title()

In [17]:
# strip the extra spaces from column names

df.columns=df.columns.str.strip()
df.columns

Index(['title', 'price', 'rating', 'brand', 'ram', 'ssd_storage', 'color',
       'processor'],
      dtype='str')

In [18]:
# fill the nan values int the color column

df['color']=df['color'].fillna("Unknown")

In [19]:
# replace the unvalid spelling in color column

df['color']=df['color'].str.replace({
    "Grey":"Gray"
})

In [20]:
# processsor column cleaning

# fill the nan values

df['processor']=df['processor'].fillna("Unknown")

# now all the column values in title foray

df["processor"]=df['processor'].str.strip().str.title()

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        550 non-null    str
 1   price        543 non-null    float64
 2   rating       501 non-null    float64
 3   brand        550 non-null    str
 4   ram          550 non-null    int64
 5   ssd_storage  550 non-null    int64
 6   color        550 non-null    str
 7   processor    550 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 34.5 KB

In [22]:
df.dtypes

title              str
price          float64
rating         float64
brand              str
ram              int64
ssd_storage      int64
color              str
processor          str
dtype: object

In [27]:
df.drop('title', axis=1, inplace=True)

In [28]:
df.to_csv("Cleaned_Laptops.csv")